# Generated by Django 4.2.4 on 2023-08-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=50)),
                ('To', models.CharField(max_length=50)),
                ('Depart_date', models.DateField()),
                ('Return_date', models.DateField()),
                ('Class', models.CharField(default='', max_length=50)),
                ('No_of_person', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=50)),
                ('depart_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
